<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Windows x64 -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>

		<!-- SELF-CONTAINED -->
		<SelfContained>true</SelfContained>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Properties\PublishProfiles\" />
	</ItemGroup>

</Project>