<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Konsol siyah ekranını tamamen iptal edip Windows formuna çevirir -->
		<OutputType>WinExe</OutputType>

		<!-- Windows Forms -->
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>

		<!-- Genel ayarlar -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- SELF-CONTAINED -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>

	</PropertyGroup>

</Project>